version: '3.8'
services:
  jenkins:
    privileged: true
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins_jcasc
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./jenkins_home:/var/jenkins_home
     - ./jcasc:/var/jcasc
     - ./plugins:/var/plugins
    environment:
     - CASC_JENKINS_CONFIG=/var/jcasc
